version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - back.local
    volumes:
      - ./docker/nginx/logs:/logs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./frontend:/var/www/frontend:cached
      - ./backend:/var/www/backend:cached
    depends_on:
      - php
      - nuxt

  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./backend:/var/www/backend:cached
    depends_on:
      - mysql

  nuxt:
    build:
      context: ./docker/nuxt
    container_name: nuxt
    volumes:
      - ./frontend:/app:cached
    ports:
      - "3000:3000"
    environment:
      - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/studio_reservation_management.local.crt

  mysql:
    image: mysql:8.0.37
    container_name: mysql
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  redis:
    image: redis:8.0.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit:v1.25.0
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      TZ: Asia/Tokyo

volumes:
  db_data:
  redis_data:
